package sg.com.temasys.skylink.sdk.sampleapp.utils;

public enum MessageRowType {
    CHAT_METADATA,
    CHAT_METADATA_MSG_HISTORY,
    CHAT_LOCAL_GRP_SIG,
    CHAT_LOCAL_GRP_P2P,
    CHAT_LOCAL_PTE_SIG,
    CHAT_LOCAL_PTE_P2P,
    CHAT_REMOTE_GRP_SIG_HISTORY,
    CHAT_REMOTE_GRP_SIG,
    CHAT_REMOTE_GRP_P2P,
    CHAT_REMOTE_PTE_SIG,
    CHAT_REMOTE_PTE_P2P
}
